### ISSUE TITLE
(Windows) Conflicting File Name

### ISSUE THREAD

**Issue by FelesNoctis** [KarlsRepo/DMus_LH#1]
It looks like you may have two files named too similarly for Windows. Appears to be one with an uppercase `L` and one with a lowercase `l`. I thought it was an `I` at first. They do appear to be unique files, not just a duplicate, but they are the same song. The one with the uppercase `L` is twice as long, but lowercase `l` loops much better.

```
D_DM2TTL.mp3 - error near the end that disrupts looping
D_DM2TTl.mp3 - loops correctly
```

![example](https://i.imgur.com/2BCJ0jK.png)

**Comment by KarlsRepo** [comment]
Yep, the lowercase one is the actual file. Just rename the file or download it again. Thanks for the report, mate.
